#!/bin/bash

echo "🚀 Scratcher Service Deployment Helper"
echo "======================================"
echo ""

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Please run this from the external-service directory"
    exit 1
fi

echo "📋 Step 1: Push to GitHub"
echo "------------------------"
echo ""
echo "I've initialized git and committed your files."
echo "Now you need to create a GitHub repository."
echo ""
echo "Option 1 - Install GitHub CLI (Recommended):"
echo "  brew install gh"
echo "  gh auth login"
echo "  gh repo create scratcher-service --public --source=. --remote=origin --push"
echo ""
echo "Option 2 - Manual:"
echo "  1. Go to https://github.com/new"
echo "  2. Create repository named 'scratcher-service'"
echo "  3. Run these commands:"
echo "     git remote add origin https://github.com/YOUR-USERNAME/scratcher-service.git"
echo "     git push -u origin main"
echo ""
read -p "Press Enter when you've pushed to GitHub..."

echo ""
echo "✅ Great! Your code is on GitHub"
echo ""

echo "📋 Step 2: Deploy on Railway"
echo "----------------------------"
echo ""
echo "Opening Railway in your browser..."
open "https://railway.app/new"
echo ""
echo "In Railway:"
echo "  1. Sign in with GitHub"
echo "  2. Click 'Deploy from GitHub repo'"
echo "  3. Select 'scratcher-service'"
echo "  4. Click 'Deploy Now'"
echo ""
read -p "Press Enter when Railway has deployed..."

echo ""
echo "✅ Service deployed!"
echo ""

echo "📋 Step 3: Add PostgreSQL"
echo "-------------------------"
echo ""
echo "In Railway dashboard:"
echo "  1. Click 'New' → 'Database' → 'Add PostgreSQL'"
echo "  2. Wait for it to provision"
echo ""
read -p "Press Enter when PostgreSQL is added..."

echo ""
echo "✅ Database added!"
echo ""

echo "📋 Step 4: Set Environment Variables"
echo "------------------------------------"
echo ""
echo "Generating API key..."
API_KEY=$(openssl rand -hex 32)
echo "API Key: $API_KEY"
echo ""
echo "In Railway dashboard:"
echo "  1. Click your service (not database)"
echo "  2. Go to 'Variables' tab"
echo "  3. Click 'Raw Editor'"
echo "  4. Paste this:"
echo ""
echo "SF_LOGIN_URL=https://login.salesforce.com"
echo "SF_USERNAME=youssef.ahmani@playful-panda-a61dyz.com"
read -p "Enter your Salesforce password: " SF_PASSWORD
read -p "Enter your Salesforce security token: " SF_TOKEN
echo "SF_PASSWORD=$SF_PASSWORD"
echo "SF_SECURITY_TOKEN=$SF_TOKEN"
echo "API_KEY=$API_KEY"
echo "CORS_ORIGIN=https://playful-panda-a61dyz-dev-ed.my.salesforce.com"
echo "POLL_INTERVAL_MINUTES=5"
echo "MAX_CHANGES_PER_ORG=50"
echo "NODE_ENV=production"
echo "PORT=3000"
echo ""
echo "  5. Click 'Update Variables'"
echo ""
read -p "Press Enter when variables are set..."

echo ""
echo "✅ Variables configured!"
echo ""

echo "📋 Step 5: Get Railway URL"
echo "--------------------------"
echo ""
echo "In Railway dashboard:"
echo "  1. Click 'Settings' tab"
echo "  2. Scroll to 'Domains'"
echo "  3. Click 'Generate Domain'"
echo ""
read -p "Enter your Railway URL (e.g., scratcher-production.up.railway.app): " RAILWAY_URL

echo ""
echo "✅ URL: https://$RAILWAY_URL"
echo ""

echo "📋 Step 6: Test Deployment"
echo "--------------------------"
echo ""
echo "Testing health endpoint..."
sleep 5
curl "https://$RAILWAY_URL/health"
echo ""
echo ""
echo "Testing API endpoint..."
curl -H "X-API-Key: $API_KEY" "https://$RAILWAY_URL/api/changes"
echo ""
echo ""

echo "📋 Step 7: Configure Salesforce"
echo "--------------------------------"
echo ""
echo "1. Add Remote Site Setting:"
echo "   - Setup → Remote Site Settings → New"
echo "   - Name: Scratcher_Railway"
echo "   - URL: https://$RAILWAY_URL"
echo ""
echo "2. Update ScratcherExternalService.cls:"
echo ""
echo "   private static String getServiceUrl() {"
echo "       return 'https://$RAILWAY_URL';"
echo "   }"
echo ""
echo "   private static String getApiKey() {"
echo "       return '$API_KEY';"
echo "   }"
echo ""
echo "3. Deploy to Salesforce:"
echo "   cd .."
echo "   sf project deploy start --source-dir force-app/main/default/classes/ScratcherExternalService.cls"
echo ""
read -p "Press Enter when Salesforce is configured..."

echo ""
echo "🎉 DEPLOYMENT COMPLETE!"
echo "======================"
echo ""
echo "Your multi-org source tracker is live at:"
echo "  https://$RAILWAY_URL"
echo ""
echo "API Key: $API_KEY"
echo ""
echo "Next steps:"
echo "  1. Open your DevHub org"
echo "  2. Navigate to the Scratcher page"
echo "  3. See changes from ALL your scratch orgs!"
echo ""
echo "Monitor your deployment:"
echo "  - Railway dashboard: https://railway.app"
echo "  - View logs: railway logs"
echo "  - Check database: railway connect postgres"
echo ""
echo "Cost: $0/month (within Railway's $5 free credit)"
echo ""
echo "Enjoy! 🚀"
